services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Answear\Payum\PayU\:
        resource: '../../../src/{Request,Service}'

    Answear\Payum\PayU\Action\:
        resource: '../../../src/Action/*'
        public: true
        shared: false

    Answear\Payum\PayU\Client\Client: ~
